apiVersion: v1
kind: Namespace
metadata:
  name: prod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whometa-flow
  namespace: prod
  labels:
    app: whometa-flow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whometa-flow
  template:
    metadata:
      labels:
        app: whometa-flow
    spec:
      containers:
      - name: whometa-flow
        image: wmacs.azurecr.io/whometa/whometa-flow:latest # Passen Sie das Docker-Image an
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: whometa-flow-service
  namespace: prod
  labels:
    app: whometa-flow
spec:
  selector:
    app: whometa-flow
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whometa-flow-cert
  namespace: prod
spec:
  secretName: whometa-flow-tls
  issuerRef:
    name: letsencrypt-azure
    kind: ClusterIssuer
  commonName: flow.whometa.eu
  dnsNames:
  - flow.whometa.eu
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whometa-flow-ingress
  namespace: prod
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-azure
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - flow.whometa.eu
    secretName: whometa-flow-tls
  rules:
  - host: flow.whometa.eu
    http:
      paths:
      - path: /core
        pathType: Prefix
        backend:
          service:
            name: whometa-flow-service
            port:
              number: 80
              paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whometa-flow-service
            port:
              number: 80
