apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-databases-flow
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: azure-managed-disk
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-flow
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: azure-managed-disk
  resources:
    requests:
      storage: 1Gi
